
export const emails = [
    'mario.hernandezramirez@upaep.mx',
    'aaron.minutti@upaep.mx',
    'andreasarahi.carmona@upaep.mx',
    'aranzapamela.garcia@upaep.mx',
    'ariadne.garcia@upaep.mx',
    'camila.cuaxiloa@upaep.mx',
    'camila.graciano@upaep.mx',
    'carlosmichel.delarosa@upaep.mx',
    'cesar.ramirez01@upaep.mx',
    'daniel.pulido@upaep.mx',
    'daniellintaro.rosales@upaep.mx',
    'dario.aguirre@upaep.mx',
    'elianemmanuel.flores@upaep.mx',
    'felipealejandro.sivilla@upaep.mx',
    'janellyabigail.reyes@upaep.mx',
    'janetmichelle.gomez@upaep.mx',
    'joseantonio.armendia@upaep.mx',
    'karime.reyes@upaep.mx',
    'katiaceylam.mota@upaep.mx',
    'luisangel.castaneda@upaep.mx',
    'marcoantonio.taboada@upaep.mx',
    'mariateresa.gomez@upaep.mx',
    'miranda.garcia@upaep.mx',
    'natalia.hernandez@upaep.mx',
    'patricio.reyes@upaep.mx',
    'ricardo.ignacio@upaep.mx',
    'sofia.castaneda@upaep.mx',
    'soniaisabel.casanova@upaep.mx',
  ];
  