export const frases = [
    "Cero y uno dan forma al código.",
    "En binario, la información se cifra.",
    "Bits bailando en el lenguaje binario.",
    "Código binario, clave del digital.",
    "El binario es la lengua de las máquinas.",
    "Letras ocultas en el código 010101.",
    "El binario revela secretos digitales.",
    "Bits y letras en perfecta armonía.",
    "El binario traduce letras en bytes.",
     "Secreto guardado en ceros y unos.",
     "Código binario, poesía de la máquina.",
     "El lenguaje binario es una danza.",
     "Bits y letras entrelazados sutilmente.",
     "Cifra tus pensamientos en binario.",
     "La magia oculta detrás del 0101.",
     "El binario susurra letras a las máquinas.",
     "La esencia de las letras es binaria.",
     "Código binario, alfabeto digital.",
     "Las letras bailan en código binario.",
     "Binario: letras en su forma pura.",
     "El código binario habla en caracteres.",
     "Letras transformadas en dígitos binarios.",
     "El binario es el lienzo de las letras.",
     "En binario, cada letra es un secreto.",
     "Código binario, gramática de la máquina.",
     "Las letras encuentran su hogar en binario.",
     "En el binario, las letras se revelan.",
     "Cada bit cuenta una historia de letras.",
     "Código binario: letras en versión digital.",
     "El binario teje palabras en su tejido.",
  ];
  